version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1

  db:
    image: postgres
    environment:
      - POSTGRES_DB=vector_data
      - POSTGRES_USER=vector_user
      - POSTGRES_PASSWORD=vector_password
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: